#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-cool-app
  tags:
    - java
spec:
  type: service
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/my-cool-app-acr